-- Deprecated migration kept for ordering compatibility.
-- Tenancy source of truth is public.center_users.
-- Pricing source of truth is public.product_prices (center override + tier fallback).
-- No schema changes are applied in this migration.
